memory_limit = 512M
max_execution_time = 300
max_input_time = 300

upload_max_filesize = 100M
post_max_size = 100M

file_uploads = On

display_errors = Off
log_errors = On

date.timezone = UTC

expose_php = Off