<?php

return [
    [
        'label' => 'الصفحة الرئيسية',
        'route' => 'admin.dashboard',
        'icon' => 'ri-home-4-line',
        'color' => 'blue',
        'permission' => 'dashboard-view',
    ],
    [
        'label' => 'الصلاحيات',
        'route' => 'roles.index',
        'icon' => 'ri-shield-keyhole-line',
        'color' => 'pink',
        'permission' => 'role-list',
    ],
    [
        'label' => 'المستخدمون',
        'route' => 'users.index',
        'icon' => 'ri-group-line',
        'color' => 'teal',
        'permission' => 'user-list',
    ],
    [
        'label' => 'الهيكل التنظيمي',
        'icon' => 'ri-organization-chart',
        'color' => 'pink',
        'children' => [
            ['label' => 'المراحل التعليمية', 'route' => 'admin.grades.index', 'icon' => 'ri-stack-line', 'color' => 'purple', 'permission' => 'grade-level-list'],
            ['label' => 'الصفوف الدراسية', 'route' => 'admin.classes.index', 'icon' => 'ri-building-2-line', 'color' => 'blue', 'permission' => 'class-list'],
            ['label' => 'الفصول الدراسية', 'route' => 'admin.sections.index', 'icon' => 'ri-layout-grid-line', 'color' => 'teal', 'permission' => 'section-list'],
            ['label' => 'المواد الدراسية', 'route' => 'admin.subjects.index', 'icon' => 'ri-book-open-line', 'color' => 'orange', 'permission' => 'subject-list'],
        ],
    ],
    [
        'label' => 'المعلمون',
        'route' => 'admin.teachers.index',
        'icon' => 'ri-user-star-line',
        'color' => 'cyan',
        'permission' => 'teacher-list',
    ],
    [
        'label' => 'الطلاب',
        'route' => 'admin.students.index',
        'icon' => 'ri-graduation-cap-line',
        'color' => 'orange',
        'permission' => 'student-list',
    ],
    [
        'label' => 'الحضور والغياب',
        'route' => 'admin.attendances.index',
        'icon' => 'ri-calendar-check-line',
        'color' => 'green',
        'permission' => 'attendance-list',
    ],
    [
        'label' => 'الجدول الدراسي',
        'route' => 'admin.schedules.index',
        'icon' => 'ri-calendar-schedule-line',
        'color' => 'blue',
        'permission' => 'schedule-list',
    ],
    [
        'label' => 'الدرجات والتقييم',
        'route' => 'admin.grade-records.index',
        'icon' => 'ri-bar-chart-box-line',
        'color' => 'yellow',
        'permission' => 'grade-list',
    ],
    [
        'label' => 'النظام المالي',
        'icon' => 'ri-money-dollar-circle-line',
        'color' => 'green',
        'children' => [
            ['label' => 'أنواع الرسوم', 'route' => 'admin.fee-types.index', 'icon' => 'ri-price-tag-3-line', 'color' => 'green', 'permission' => 'fee-type-list'],
            ['label' => 'الفواتير', 'route' => 'admin.invoices.index', 'icon' => 'ri-file-list-3-line', 'color' => 'blue', 'permission' => 'invoice-list'],
            ['label' => 'المدفوعات', 'route' => 'admin.payments.index', 'icon' => 'ri-wallet-3-line', 'color' => 'teal', 'permission' => 'payment-list'],
            ['label' => 'الحسابات المالية', 'route' => 'admin.financial-accounts.index', 'icon' => 'ri-bank-line', 'color' => 'purple', 'permission' => 'financial-account-list'],
        ],
    ],
    [
        'label' => 'نظام المكتبة',
        'icon' => 'ri-book-2-line',
        'color' => 'brown',
        'children' => [
            ['label' => 'تصنيفات الكتب', 'route' => 'admin.book-categories.index', 'icon' => 'ri-bookmark-line', 'color' => 'brown', 'permission' => 'book-category-list'],
            ['label' => 'الكتب', 'route' => 'admin.books.index', 'icon' => 'ri-book-line', 'color' => 'orange', 'permission' => 'book-list'],
            ['label' => 'الاستعارات', 'route' => 'admin.book-borrowings.index', 'icon' => 'ri-exchange-line', 'color' => 'blue', 'permission' => 'book-borrowing-list'],
            ['label' => 'الغرامات', 'route' => 'admin.fines.index', 'icon' => 'ri-error-warning-line', 'color' => 'red', 'permission' => 'fine-list'],
        ],
    ],
    [
        'label' => 'الواجبات',
        'route' => 'admin.assignments.index',
        'icon' => 'ri-file-text-line',
        'color' => 'orange',
        'permission' => 'assignment-list',
    ],
    [
        'label' => 'بنك الأسئلة',
        'icon' => 'ri-questionnaire-line',
        'color' => 'purple',
        'children' => [
            ['label' => 'الأسئلة', 'route' => 'admin.questions.index', 'icon' => 'ri-question-line', 'color' => 'purple', 'permission' => 'question-list'],
            ['label' => 'معايير التقييم', 'route' => 'admin.rubrics.index', 'icon' => 'ri-list-check-2', 'color' => 'pink', 'permission' => 'rubric-list'],
        ],
    ],
    [
        'label' => 'الاختبارات',
        'icon' => 'ri-survey-line',
        'color' => 'pink',
        'children' => [
            ['label' => 'الاختبارات', 'route' => 'admin.exams.index', 'icon' => 'ri-file-edit-line', 'color' => 'pink', 'permission' => 'exam-list'],
            ['label' => 'نتائج الاختبارات', 'route' => 'admin.exam-results.index', 'icon' => 'ri-trophy-line', 'color' => 'yellow', 'permission' => 'exam-result-list'],
            ['label' => 'إجابات الطلاب', 'route' => 'admin.exam-answers.index', 'icon' => 'ri-chat-check-line', 'color' => 'blue', 'permission' => 'exam-answer-list'],
            ['label' => 'تقييمات الأسئلة المقالية', 'route' => 'admin.essay-evaluations.index', 'icon' => 'ri-quill-pen-line', 'color' => 'teal', 'permission' => 'essay-evaluation-list'],
        ],
    ],
    [
        'label' => 'المحاضرات الإلكترونية',
        'icon' => 'ri-live-line',
        'color' => 'purple',
        'children' => [
            ['label' => 'المحاضرات', 'route' => 'admin.online-lectures.index', 'icon' => 'ri-video-line', 'color' => 'purple', 'permission' => 'lecture-list'],
            ['label' => 'المواد التعليمية', 'route' => 'admin.lecture-materials.index', 'icon' => 'ri-folder-video-line', 'color' => 'blue', 'permission' => 'lecture-material-list'],
            ['label' => 'حضور المحاضرات', 'route' => 'admin.lecture-attendance.index', 'icon' => 'ri-user-follow-line', 'color' => 'green', 'permission' => 'lecture-attendance-list'],
        ],
    ],
    [
        'label' => 'التقارير',
        'icon' => 'ri-file-chart-line',
        'color' => 'blue',
        'children' => [
            ['label' => 'جميع التقارير', 'route' => 'admin.reports.index', 'icon' => 'ri-file-chart-line', 'color' => 'blue', 'permission' => 'report-list'],
            ['label' => 'إنشاء تقرير جديد', 'route' => 'admin.reports.create', 'icon' => 'ri-file-add-line', 'color' => 'green', 'permission' => 'report-create'],
            ['label' => 'أداء الطلاب', 'route' => 'admin.reports.student-performance', 'icon' => 'ri-line-chart-line', 'color' => 'purple', 'permission' => 'report-student-performance'],
            ['label' => 'أداء الفصول', 'route' => 'admin.reports.class-performance', 'icon' => 'ri-bar-chart-grouped-line', 'color' => 'teal', 'permission' => 'report-class-performance'],
            ['label' => 'أداء المعلمين', 'route' => 'admin.reports.teacher-performance', 'icon' => 'ri-user-search-line', 'color' => 'cyan', 'permission' => 'report-teacher-performance'],
            ['label' => 'الحضور والغياب', 'route' => 'admin.reports.attendance', 'icon' => 'ri-calendar-check-line', 'color' => 'green', 'permission' => 'report-attendance'],
            ['label' => 'التقارير المالية', 'route' => 'admin.reports.financial', 'icon' => 'ri-money-dollar-box-line', 'color' => 'green', 'permission' => 'report-financial'],
            ['label' => 'المكتبة', 'route' => 'admin.reports.library', 'icon' => 'ri-book-2-line', 'color' => 'brown', 'permission' => 'report-library'],
            ['label' => 'الاختبارات', 'route' => 'admin.reports.exams', 'icon' => 'ri-survey-line', 'color' => 'pink', 'permission' => 'report-exams'],
            ['label' => 'الواجبات', 'route' => 'admin.reports.assignments', 'icon' => 'ri-file-text-line', 'color' => 'orange', 'permission' => 'report-assignments'],
            ['label' => 'الدرجات', 'route' => 'admin.reports.grades', 'icon' => 'ri-award-line', 'color' => 'yellow', 'permission' => 'report-grades'],
        ],
    ],
    [
        'label' => 'الأحداث والتقويم',
        'icon' => 'ri-calendar-event-line',
        'color' => 'red',
        'children' => [
            ['label' => 'جميع الأحداث', 'route' => 'admin.events.index', 'icon' => 'ri-calendar-event-line', 'color' => 'red', 'permission' => 'event-list'],
            ['label' => 'إضافة حدث جديد', 'route' => 'admin.events.create', 'icon' => 'ri-calendar-todo-line', 'color' => 'orange', 'permission' => 'event-create'],
            ['label' => 'التقويم الشهري', 'route' => 'admin.calendar.month', 'icon' => 'ri-calendar-line', 'color' => 'blue', 'permission' => 'calendar-view'],
            ['label' => 'التقويم الأسبوعي', 'route' => 'admin.calendar.week', 'icon' => 'ri-calendar-2-line', 'color' => 'teal', 'permission' => 'calendar-view'],
            ['label' => 'التقويم اليومي', 'route' => 'admin.calendar.day', 'icon' => 'ri-time-line', 'color' => 'purple', 'permission' => 'calendar-view'],
            ['label' => 'التقويم الأكاديمي', 'route' => 'admin.academic-calendars.index', 'icon' => 'ri-calendar-check-line', 'color' => 'green', 'permission' => 'academic-calendar-list'],
        ],
    ],
    [
        'label' => 'الشهادات',
        'icon' => 'ri-award-line',
        'color' => 'gold',
        'children' => [
            ['label' => 'جميع الشهادات', 'route' => 'admin.certificates.index', 'icon' => 'ri-award-line', 'color' => 'gold', 'permission' => 'certificate-list'],
            ['label' => 'إضافة شهادة', 'route' => 'admin.certificates.create', 'icon' => 'ri-medal-line', 'color' => 'yellow', 'permission' => 'certificate-create'],
            ['label' => 'قوالب الشهادات', 'route' => 'admin.certificate-templates.index', 'icon' => 'ri-layout-masonry-line', 'color' => 'purple', 'permission' => 'certificate-template-list'],
        ],
    ],
    [
        'label' => 'إدارة النقل',
        'icon' => 'ri-bus-line',
        'color' => 'cyan',
        'children' => [
            ['label' => 'مسارات الحافلات', 'route' => 'admin.bus-routes.index', 'icon' => 'ri-route-line', 'color' => 'cyan', 'permission' => 'bus-route-list'],
            ['label' => 'محطات الحافلات', 'route' => 'admin.bus-stops.index', 'icon' => 'ri-map-pin-line', 'color' => 'red', 'permission' => 'bus-stop-list'],
            ['label' => 'السائقون', 'route' => 'admin.drivers.index', 'icon' => 'ri-steering-2-line', 'color' => 'blue', 'permission' => 'driver-list'],
            ['label' => 'المشرفون', 'route' => 'admin.supervisors.index', 'icon' => 'ri-user-settings-line', 'color' => 'purple', 'permission' => 'supervisor-list'],
            ['label' => 'نقل الطلاب', 'route' => 'admin.student-transports.index', 'icon' => 'ri-bus-2-line', 'color' => 'teal', 'permission' => 'student-transport-list'],
        ],
    ],
    [
        'label' => 'إدارة السكن',
        'icon' => 'ri-home-smile-line',
        'color' => 'indigo',
        'children' => [
            ['label' => 'النزل', 'route' => 'admin.hostels.index', 'icon' => 'ri-building-line', 'color' => 'indigo', 'permission' => 'hostel-list'],
            ['label' => 'الغرف', 'route' => 'admin.rooms.index', 'icon' => 'ri-door-open-line', 'color' => 'blue', 'permission' => 'room-list'],
            ['label' => 'إقامة الطلاب', 'route' => 'admin.student-accommodations.index', 'icon' => 'ri-hotel-bed-line', 'color' => 'teal', 'permission' => 'student-accommodation-list'],
            ['label' => 'الزوار', 'route' => 'admin.visitors.index', 'icon' => 'ri-user-shared-line', 'color' => 'orange', 'permission' => 'visitor-list'],
        ],
    ],
    [
        'label' => 'إدارة الخريجين',
        'icon' => 'ri-team-line',
        'color' => 'teal',
        'children' => [
            ['label' => 'الخريجون', 'route' => 'admin.alumni.index', 'icon' => 'ri-graduation-cap-line', 'color' => 'teal', 'permission' => 'alumni-list'],
            ['label' => 'أحداث الخريجين', 'route' => 'admin.alumni-events.index', 'icon' => 'ri-calendar-star-line', 'color' => 'gold', 'permission' => 'alumni-event-list'],
            ['label' => 'الوظائف المفتوحة', 'route' => 'admin.job-postings.index', 'icon' => 'ri-briefcase-line', 'color' => 'blue', 'permission' => 'job-posting-list'],
            ['label' => 'التبرعات', 'route' => 'admin.alumni-donations.index', 'icon' => 'ri-hand-heart-line', 'color' => 'pink', 'permission' => 'alumni-donation-list'],
        ],
    ],
];
