<?php

/**
 * سجل الصلاحيات المركزي — Edu-System
 * المفتاح: اسم الصلاحية | القيمة: التسمية العربية
 */
return [

    'groups' => [

        'system' => [
            'label' => 'النظام',
            'permissions' => [
                'dashboard-view' => 'عرض لوحة التحكم',
                'settings-manage' => 'إدارة الإعدادات',
            ],
        ],

        'roles_users' => [
            'label' => 'الأدوار والمستخدمون',
            'permissions' => [
                'role-list' => 'عرض الأدوار',
                'role-create' => 'إنشاء دور',
                'role-edit' => 'تعديل دور',
                'role-delete' => 'حذف دور',
                'user-list' => 'عرض المستخدمين',
                'user-create' => 'إنشاء مستخدم',
                'user-edit' => 'تعديل مستخدم',
                'user-delete' => 'حذف مستخدم',
                'user-show' => 'عرض تفاصيل مستخدم',
                'user-update-password' => 'تغيير كلمة مرور مستخدم',
                'user-toggle-status' => 'تفعيل/تعطيل مستخدم',
            ],
        ],

        'academic_structure' => [
            'label' => 'الهيكل التنظيمي',
            'permissions' => [
                'grade-level-list' => 'عرض المراحل التعليمية',
                'grade-level-create' => 'إنشاء مرحلة',
                'grade-level-edit' => 'تعديل مرحلة',
                'grade-level-delete' => 'حذف مرحلة',
                'class-list' => 'عرض الصفوف',
                'class-create' => 'إنشاء صف',
                'class-edit' => 'تعديل صف',
                'class-delete' => 'حذف صف',
                'section-list' => 'عرض الفصول',
                'section-create' => 'إنشاء فصل',
                'section-edit' => 'تعديل فصل',
                'section-delete' => 'حذف فصل',
                'subject-list' => 'عرض المواد',
                'subject-create' => 'إنشاء مادة',
                'subject-edit' => 'تعديل مادة',
                'subject-delete' => 'حذف مادة',
                'teacher-list' => 'عرض المعلمين',
                'teacher-create' => 'إضافة معلم',
                'teacher-edit' => 'تعديل معلم',
                'teacher-delete' => 'حذف معلم',
                'teacher-show' => 'عرض تفاصيل معلم',
            ],
        ],

        'students' => [
            'label' => 'الطلاب',
            'permissions' => [
                'student-list' => 'عرض الطلاب',
                'student-create' => 'إضافة طالب',
                'student-edit' => 'تعديل طالب',
                'student-delete' => 'حذف طالب',
                'student-show' => 'عرض تفاصيل طالب',
            ],
        ],

        'attendance' => [
            'label' => 'الحضور والغياب',
            'permissions' => [
                'attendance-list' => 'عرض الحضور',
                'attendance-create' => 'تسجيل حضور',
                'attendance-edit' => 'تعديل حضور',
                'attendance-delete' => 'حذف حضور',
                'attendance-view' => 'عرض تفاصيل حضور',
            ],
        ],

        'schedule' => [
            'label' => 'الجدول الدراسي',
            'permissions' => [
                'schedule-list' => 'عرض الجدول',
                'schedule-create' => 'إنشاء حصة',
                'schedule-edit' => 'تعديل حصة',
                'schedule-delete' => 'حذف حصة',
                'schedule-view' => 'عرض تفاصيل حصة',
            ],
        ],

        'grade_records' => [
            'label' => 'الدرجات والتقييم',
            'permissions' => [
                'grade-list' => 'عرض سجلات الدرجات',
                'grade-create' => 'إضافة درجة',
                'grade-edit' => 'تعديل درجة',
                'grade-delete' => 'حذف درجة',
                'grade-view' => 'عرض تفاصيل درجة',
            ],
        ],

        'financial' => [
            'label' => 'النظام المالي',
            'permissions' => [
                'fee-type-list' => 'عرض أنواع الرسوم',
                'fee-type-create' => 'إنشاء نوع رسوم',
                'fee-type-edit' => 'تعديل نوع رسوم',
                'fee-type-delete' => 'حذف نوع رسوم',
                'invoice-list' => 'عرض الفواتير',
                'invoice-create' => 'إنشاء فاتورة',
                'invoice-edit' => 'تعديل فاتورة',
                'invoice-delete' => 'حذف فاتورة',
                'invoice-view' => 'عرض تفاصيل فاتورة',
                'payment-list' => 'عرض المدفوعات',
                'payment-create' => 'تسجيل دفعة',
                'payment-edit' => 'تعديل دفعة',
                'payment-delete' => 'حذف دفعة',
                'payment-view' => 'عرض تفاصيل دفعة',
                'financial-account-list' => 'عرض الحسابات المالية',
                'financial-account-view' => 'عرض تفاصيل حساب مالي',
            ],
        ],

        'library' => [
            'label' => 'المكتبة',
            'permissions' => [
                'book-category-list' => 'عرض تصنيفات الكتب',
                'book-category-create' => 'إنشاء تصنيف',
                'book-category-edit' => 'تعديل تصنيف',
                'book-category-delete' => 'حذف تصنيف',
                'book-list' => 'عرض الكتب',
                'book-create' => 'إضافة كتاب',
                'book-edit' => 'تعديل كتاب',
                'book-delete' => 'حذف كتاب',
                'book-borrowing-list' => 'عرض الاستعارات',
                'book-borrowing-create' => 'إنشاء استعارة',
                'book-borrowing-edit' => 'تعديل استعارة',
                'book-borrowing-delete' => 'حذف استعارة',
                'book-borrowing-return' => 'إرجاع كتاب',
                'fine-list' => 'عرض الغرامات',
                'fine-create' => 'إنشاء غرامة',
                'fine-edit' => 'تعديل غرامة',
                'fine-delete' => 'حذف غرامة',
                'fine-pay' => 'تسديد غرامة',
            ],
        ],

        'lectures' => [
            'label' => 'المحاضرات الإلكترونية',
            'permissions' => [
                'lecture-list' => 'عرض المحاضرات',
                'lecture-create' => 'إنشاء محاضرة',
                'lecture-edit' => 'تعديل محاضرة',
                'lecture-delete' => 'حذف محاضرة',
                'lecture-material-list' => 'عرض المواد التعليمية',
                'lecture-material-create' => 'إضافة مادة',
                'lecture-material-edit' => 'تعديل مادة',
                'lecture-material-delete' => 'حذف مادة',
                'lecture-attendance-list' => 'عرض حضور المحاضرات',
                'lecture-attendance-create' => 'تسجيل حضور محاضرة',
                'lecture-attendance-edit' => 'تعديل حضور محاضرة',
                'lecture-attendance-delete' => 'حذف حضور محاضرة',
            ],
        ],

        'assignments' => [
            'label' => 'الواجبات',
            'permissions' => [
                'assignment-list' => 'عرض الواجبات',
                'assignment-create' => 'إنشاء واجب',
                'assignment-edit' => 'تعديل واجب',
                'assignment-delete' => 'حذف واجب',
                'assignment-view' => 'عرض تفاصيل واجب',
                'assignment-publish' => 'نشر/إغلاق واجب',
                'assignment-submission-list' => 'عرض تسليمات الواجبات',
                'assignment-submission-view' => 'عرض تسليم واجب',
                'assignment-submission-grade' => 'تقييم تسليم واجب',
                'assignment-submit' => 'تسليم واجب (طالب)',
            ],
        ],

        'exams' => [
            'label' => 'الاختبارات وبنك الأسئلة',
            'permissions' => [
                'question-list' => 'عرض الأسئلة',
                'question-create' => 'إنشاء سؤال',
                'question-edit' => 'تعديل سؤال',
                'question-delete' => 'حذف سؤال',
                'rubric-list' => 'عرض معايير التقييم',
                'rubric-create' => 'إنشاء معيار',
                'rubric-edit' => 'تعديل معيار',
                'rubric-delete' => 'حذف معيار',
                'exam-list' => 'عرض الاختبارات',
                'exam-create' => 'إنشاء اختبار',
                'exam-edit' => 'تعديل اختبار',
                'exam-delete' => 'حذف اختبار',
                'exam-show' => 'عرض تفاصيل اختبار',
                'exam-publish' => 'نشر/إلغاء نشر اختبار',
                'exam-question-manage' => 'إدارة أسئلة الاختبار',
                'exam-answer-list' => 'عرض إجابات الطلاب',
                'exam-answer-edit' => 'تعديل إجابة',
                'exam-answer-delete' => 'حذف إجابة',
                'exam-answer-auto-grade' => 'تصحيح تلقائي',
                'exam-result-list' => 'عرض نتائج الاختبارات',
                'exam-result-show' => 'عرض نتيجة',
                'exam-result-edit' => 'تعديل نتيجة',
                'exam-result-delete' => 'حذف نتيجة',
                'exam-result-export' => 'تصدير نتائج',
                'essay-evaluation-list' => 'عرض تقييمات المقالية',
                'essay-evaluation-create' => 'إنشاء تقييم مقالية',
                'essay-evaluation-edit' => 'تعديل تقييم مقالية',
                'essay-evaluation-delete' => 'حذف تقييم مقالية',
                'essay-evaluation-recalculate' => 'إعادة حساب تقييم',
            ],
        ],

        'reports' => [
            'label' => 'التقارير',
            'permissions' => [
                'report-list' => 'عرض التقارير',
                'report-create' => 'إنشاء تقرير',
                'report-export' => 'تصدير تقارير',
                'report-student-performance' => 'تقرير أداء الطلاب',
                'report-class-performance' => 'تقرير أداء الفصول',
                'report-teacher-performance' => 'تقرير أداء المعلمين',
                'report-attendance' => 'تقرير الحضور',
                'report-financial' => 'تقرير مالي',
                'report-library' => 'تقرير المكتبة',
                'report-exams' => 'تقرير الاختبارات',
                'report-assignments' => 'تقرير الواجبات',
                'report-grades' => 'تقرير الدرجات',
            ],
        ],

        'export' => [
            'label' => 'التصدير',
            'permissions' => [
                'export-students' => 'تصدير الطلاب',
                'export-teachers' => 'تصدير المعلمين',
                'export-classes' => 'تصدير الصفوف',
                'export-sections' => 'تصدير الفصول',
                'export-subjects' => 'تصدير المواد',
                'export-attendances' => 'تصدير الحضور',
                'export-grade-records' => 'تصدير الدرجات',
                'export-invoices' => 'تصدير الفواتير',
                'export-payments' => 'تصدير المدفوعات',
                'export-books' => 'تصدير الكتب',
                'export-book-borrowings' => 'تصدير الاستعارات',
                'export-exams' => 'تصدير الاختبارات',
                'export-assignments' => 'تصدير الواجبات',
            ],
        ],

        'events' => [
            'label' => 'الأحداث والتقويم',
            'permissions' => [
                'event-list' => 'عرض الأحداث',
                'event-create' => 'إنشاء حدث',
                'event-edit' => 'تعديل حدث',
                'event-delete' => 'حذف حدث',
                'event-show' => 'عرض تفاصيل حدث',
                'calendar-view' => 'عرض التقويم',
                'academic-calendar-list' => 'عرض التقويم الأكاديمي',
                'academic-calendar-create' => 'إنشاء تقويم أكاديمي',
                'academic-calendar-edit' => 'تعديل تقويم أكاديمي',
                'academic-calendar-delete' => 'حذف تقويم أكاديمي',
            ],
        ],

        'certificates' => [
            'label' => 'الشهادات',
            'permissions' => [
                'certificate-list' => 'عرض الشهادات',
                'certificate-create' => 'إصدار شهادة',
                'certificate-edit' => 'تعديل شهادة',
                'certificate-delete' => 'حذف شهادة',
                'certificate-show' => 'عرض تفاصيل شهادة',
                'certificate-template-list' => 'عرض قوالب الشهادات',
                'certificate-template-create' => 'إنشاء قالب',
                'certificate-template-edit' => 'تعديل قالب',
                'certificate-template-delete' => 'حذف قالب',
                'certificate-template-show' => 'عرض قالب',
            ],
        ],

        'transport' => [
            'label' => 'النقل',
            'permissions' => [
                'bus-route-list' => 'عرض مسارات الحافلات',
                'bus-route-create' => 'إنشاء مسار',
                'bus-route-edit' => 'تعديل مسار',
                'bus-route-delete' => 'حذف مسار',
                'bus-route-show' => 'عرض مسار',
                'bus-stop-list' => 'عرض المحطات',
                'bus-stop-create' => 'إنشاء محطة',
                'bus-stop-edit' => 'تعديل محطة',
                'bus-stop-delete' => 'حذف محطة',
                'bus-stop-show' => 'عرض محطة',
                'driver-list' => 'عرض السائقين',
                'driver-create' => 'إضافة سائق',
                'driver-edit' => 'تعديل سائق',
                'driver-delete' => 'حذف سائق',
                'driver-show' => 'عرض سائق',
                'supervisor-list' => 'عرض المشرفين',
                'supervisor-create' => 'إضافة مشرف',
                'supervisor-edit' => 'تعديل مشرف',
                'supervisor-delete' => 'حذف مشرف',
                'supervisor-show' => 'عرض مشرف',
                'student-transport-list' => 'عرض نقل الطلاب',
                'student-transport-create' => 'تسجيل نقل',
                'student-transport-edit' => 'تعديل نقل',
                'student-transport-delete' => 'حذف نقل',
                'student-transport-show' => 'عرض نقل',
            ],
        ],

        'hostel' => [
            'label' => 'السكن',
            'permissions' => [
                'hostel-list' => 'عرض النزل',
                'hostel-create' => 'إنشاء نزل',
                'hostel-edit' => 'تعديل نزل',
                'hostel-delete' => 'حذف نزل',
                'hostel-show' => 'عرض نزل',
                'room-list' => 'عرض الغرف',
                'room-create' => 'إنشاء غرفة',
                'room-edit' => 'تعديل غرفة',
                'room-delete' => 'حذف غرفة',
                'room-show' => 'عرض غرفة',
                'student-accommodation-list' => 'عرض إقامة الطلاب',
                'student-accommodation-create' => 'تسجيل إقامة',
                'student-accommodation-edit' => 'تعديل إقامة',
                'student-accommodation-delete' => 'حذف إقامة',
                'student-accommodation-show' => 'عرض إقامة',
                'visitor-list' => 'عرض الزوار',
                'visitor-create' => 'تسجيل زائر',
                'visitor-edit' => 'تعديل زائر',
                'visitor-delete' => 'حذف زائر',
                'visitor-show' => 'عرض زائر',
            ],
        ],

        'alumni' => [
            'label' => 'الخريجون',
            'permissions' => [
                'alumni-list' => 'عرض الخريجين',
                'alumni-create' => 'إضافة خريج',
                'alumni-edit' => 'تعديل خريج',
                'alumni-delete' => 'حذف خريج',
                'alumni-show' => 'عرض خريج',
                'alumni-event-list' => 'عرض أحداث الخريجين',
                'alumni-event-create' => 'إنشاء حدث',
                'alumni-event-edit' => 'تعديل حدث',
                'alumni-event-delete' => 'حذف حدث',
                'alumni-event-show' => 'عرض حدث',
                'job-posting-list' => 'عرض الوظائف',
                'job-posting-create' => 'نشر وظيفة',
                'job-posting-edit' => 'تعديل وظيفة',
                'job-posting-delete' => 'حذف وظيفة',
                'job-posting-show' => 'عرض وظيفة',
                'alumni-donation-list' => 'عرض التبرعات',
                'alumni-donation-create' => 'تسجيل تبرع',
                'alumni-donation-edit' => 'تعديل تبرع',
                'alumni-donation-delete' => 'حذف تبرع',
                'alumni-donation-show' => 'عرض تبرع',
            ],
        ],

        'smtp' => [
            'label' => 'إعدادات SMTP',
            'permissions' => [
                'smtp-setting-list' => 'عرض إعدادات SMTP',
                'smtp-setting-create' => 'إنشاء إعداد',
                'smtp-setting-edit' => 'تعديل إعداد',
                'smtp-setting-delete' => 'حذف إعداد',
                'smtp-setting-test' => 'اختبار اتصال SMTP',
            ],
        ],

        'student_portal' => [
            'label' => 'بوابة الطالب',
            'permissions' => [
                'student-dashboard-view' => 'لوحة الطالب',
                'student-grades-view' => 'عرض الدرجات',
                'student-attendance-view' => 'عرض الحضور',
                'student-schedule-view' => 'عرض الجدول',
                'student-assignments-view' => 'عرض الواجبات',
                'student-invoices-view' => 'عرض الفواتير',
                'student-profile-edit' => 'تعديل الملف الشخصي',
                'student-library-view' => 'عرض المكتبة',
                'student-lecture-view' => 'عرض المحاضرات',
                'student-exam-view' => 'عرض الاختبارات',
                'student-exam-take' => 'أداء الاختبار',
            ],
        ],

        'parent_portal' => [
            'label' => 'بوابة ولي الأمر',
            'permissions' => [
                'parent-dashboard-view' => 'لوحة ولي الأمر',
                'parent-children-view' => 'عرض الأبناء',
                'parent-grades-view' => 'عرض درجات الأبناء',
                'parent-attendance-view' => 'عرض حضور الأبناء',
                'parent-schedule-view' => 'عرض جدول الأبناء',
                'parent-assignments-view' => 'عرض واجبات الأبناء',
                'parent-invoices-view' => 'عرض فواتير الأبناء',
                'parent-messages-send' => 'إرسال رسائل',
                'parent-notifications-view' => 'عرض الإشعارات',
            ],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | صلاحيات الأدوار الافتراضية (أسماء المفاتيح فقط)
    |--------------------------------------------------------------------------
    */
    'roles' => [

        'teacher' => [
            'dashboard-view',
            'attendance-list', 'attendance-create', 'attendance-edit', 'attendance-view',
            'schedule-list', 'schedule-view',
            'grade-list', 'grade-create', 'grade-edit', 'grade-view',
            'student-list', 'student-show',
            'assignment-list', 'assignment-create', 'assignment-edit', 'assignment-view', 'assignment-publish',
            'assignment-submission-list', 'assignment-submission-view', 'assignment-submission-grade',
            'lecture-list', 'lecture-create', 'lecture-edit',
            'lecture-material-list', 'lecture-material-create', 'lecture-material-edit',
            'lecture-attendance-list', 'lecture-attendance-create', 'lecture-attendance-edit',
            'exam-list', 'exam-show', 'exam-question-manage',
            'exam-answer-list', 'exam-answer-edit', 'exam-answer-auto-grade',
            'exam-result-list', 'exam-result-show',
            'essay-evaluation-list', 'essay-evaluation-create', 'essay-evaluation-edit',
            'question-list', 'question-create', 'question-edit',
            'report-list', 'report-student-performance', 'report-class-performance', 'report-attendance', 'report-assignments', 'report-grades',
        ],

        'accountant' => [
            'dashboard-view',
            'student-list', 'student-show',
            'fee-type-list', 'fee-type-create', 'fee-type-edit',
            'invoice-list', 'invoice-create', 'invoice-edit', 'invoice-view',
            'payment-list', 'payment-create', 'payment-edit', 'payment-view',
            'financial-account-list', 'financial-account-view',
            'report-list', 'report-financial', 'report-export',
            'export-invoices', 'export-payments',
        ],

        'librarian' => [
            'dashboard-view',
            'student-list', 'student-show',
            'book-category-list', 'book-category-create', 'book-category-edit', 'book-category-delete',
            'book-list', 'book-create', 'book-edit', 'book-delete',
            'book-borrowing-list', 'book-borrowing-create', 'book-borrowing-edit', 'book-borrowing-return',
            'fine-list', 'fine-create', 'fine-edit', 'fine-pay',
            'report-list', 'report-library',
            'export-books', 'export-book-borrowings',
        ],

        'staff' => [
            'dashboard-view',
            'student-list', 'student-show',
            'teacher-list', 'teacher-show',
            'grade-level-list', 'class-list', 'section-list', 'subject-list',
            'attendance-list', 'attendance-view',
            'schedule-list', 'schedule-view',
            'event-list', 'event-show', 'calendar-view',
            'report-list',
        ],

        'student' => [
            'student-dashboard-view',
            'student-grades-view',
            'student-attendance-view',
            'student-schedule-view',
            'student-assignments-view',
            'student-invoices-view',
            'student-profile-edit',
            'student-library-view',
            'student-lecture-view',
            'student-exam-view',
            'student-exam-take',
            'assignment-submit',
        ],

        'parent' => [
            'parent-dashboard-view',
            'parent-children-view',
            'parent-grades-view',
            'parent-attendance-view',
            'parent-schedule-view',
            'parent-assignments-view',
            'parent-invoices-view',
            'parent-messages-send',
            'parent-notifications-view',
        ],
    ],
];
